# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historia_medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_historia', models.DateTimeField()),
                ('diagnostico', models.CharField(max_length=500)),
                ('tratamiento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Med_Esp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_especialidad', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gturnos.Persona')),
                ('mat_profesional', models.IntegerField()),
                ('organizaciones', models.ManyToManyField(to='gturnos.Organizacion')),
            ],
            bases=('gturnos.persona',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gturnos.Persona')),
                ('fecha_inicio', models.DateField()),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('perimetro_enc', models.IntegerField()),
            ],
            bases=('gturnos.persona',),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Sexo'),
        ),
        migrations.AddField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Medico'),
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Paciente'),
        ),
        migrations.AddField(
            model_name='rel_med_esp',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Medico'),
        ),
        migrations.AddField(
            model_name='historia_medica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Medico'),
        ),
        migrations.AddField(
            model_name='historia_medica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Paciente'),
        ),
    ]
